### ISSUE TITLE
Docker image 1.0.0 is wrong

### ISSUE THREAD

**Issue by ngosang** [DRuggeri/alertmanager_gotify_bridge#17]
The image does not start because the entrypoint is wrong. I think you should use the Dockerfile to avoid maintaining 2 files, it's error prone.
This is how I'm building images in other project => https://github.com/ngosang/urbackup-exporter/blob/master/.github/workflows/release-docker.yml#L52

**Comment by DRuggeri** [comment]
Hi, @ngosang - I had missed a push yesterday... that caused the issue. I'll cut a new release and tag as v1.0.1 shortly.

The Dockerfile in this project is not intended for use in the pipeline (I've added comments to clarify), but rather for users who would like to just build it themselves.

The pipeline will just download the release from GitHub directly into a scratch container rather than attempting to build it again. This is to minimize container size, attack surface, and to ensure that the built code is what is present in the container.

**Comment by ngosang** [comment]
Thank you. It's working now!
