### ISSUE TITLE
Latest version doesn't return version when running with --version flag.

### ISSUE THREAD

**Issue by ndragon798** [DRuggeri/alertmanager_gotify_bridge#20]
When running the latest version with the --latest flag no version is returned.

Latest version pulled with ```RUN go install github.com/DRuggeri/alertmanager_gotify_bridge@latest```

```/go # cd bin/
/go/bin # ./alertmanager_gotify_bridge --version

/go/bin #
```

**Comment by DRuggeri** [comment]
Hi, @ndragon798 - I can't explain that output since there is a default value of "testing" set for the version string... but only the GitHub Actions pipeline sets the version based on the release tag.

Here's an example of the current release:
```
hax@hax:/tmp/foo$ rm alertmanager_gotify_bridge-v1.0.3-linux-amd64
hax@hax:/tmp/foo$ wget -q https://github.com/DRuggeri/alertmanager_gotify_bridge/releases/download/v1.0.3/alertmanager_gotify_bridge-v1.0.3-linux-amd64
hax@hax:/tmp/foo$ chmod 755 alertmanager_gotify_bridge-v1.0.3-linux-amd64
hax@hax:/tmp/foo$ ./alertmanager_gotify_bridge-v1.0.3-linux-amd64 --version
1.0.3
```

And here's an example of just building as-is (note the version change):
```
hax@hax:~/go/src/github.com/DRuggeri/alertmanager_gotify_bridge$ go build && ./alertmanager_gotify_bridge --version
testing
```

That said, I don't think that the version string will show up as expected using the method you are using for installation.
