### ISSUE TITLE
The Native Alertmanager's Go Templating is not working while included in Bridge's Go Templating

### ISSUE THREAD

**Issue by destrianto** [DRuggeri/alertmanager_gotify_bridge#23]
Hi, first things first I love your work! since Prometheus at the moment has no Gotify native support for some reason. Anyway, can you look up for this problem? It seems when I'm combined your method Go Templating with the native of Alertmanager, it appears the Bridge refused it. Here's my templating:

**Summary/Title**
`{{if eq .Status "firing"}}The target "{{ $labels.instance }}" is down{{else}}The target "{{ $labels.instance }}" is recovered{{end}}`

**Description/Message**
`{{if eq .Status "firing"}}The target has not been replying for 10 minutes{{else}}The target has been replying for the last 10 seconds{{end}}`

**Bridge logs**
`Jan 06 02:18:51 gotify alertmanager_gotify_bridge[6130]: 2023/01/06 02:18:51 error in Template: template: tmp:1: undefined variable "$labels"`
`Jan 06 02:18:51 gotify alertmanager_gotify_bridge[6130]: 2023/01/06 02:18:51     title:`
`Jan 06 02:18:51 gotify alertmanager_gotify_bridge[6130]: 2023/01/06 02:18:51     message: The target has not been replying for 10 minutes`
`Jan 06 02:18:51 gotify alertmanager_gotify_bridge[6130]: 2023/01/06 02:18:51     Unable to dispatch!`

Is there any way to escape the `{{ $labels.instance }}`? I need the instance information in its own message, I mean not including all instances in one message, thank you!

**Comment by DRuggeri** [comment]
Hi, @destrianto 
This poses an interesting challenge. The native alertmanager templating should be doing the interpolation it knows about before sending the alert. To me, this should mean that `$labels` should have been resolved to a string by alertmanager before being sent to the bridge. If it isn't, this error in the bridge makes sense since nothing defines `$labels`.
I don't have specific advice to offer, but I think this error would go away if you can figure out why alertmanager doesn't turn `{{ $labels.instance }}` into the instance name before dispatching the alert to the bridge.

**Comment by DRuggeri** [comment]
I hope the above comment helped? If not, or if you have more inquiries, feel free to reopen.

**Comment by destrianto** [comment]
I'm sorry for the late respond. Yes, your explanation is clear to me. My current solution is migrated the alerting to Grafana.

Anyway, thank you for your support. Cheers!
