### ISSUE TITLE
x509: certificate signed by unknown authority accessing HTTPS gotify endpoint

### ISSUE THREAD

**Issue by evandeaubl** [DRuggeri/alertmanager_gotify_bridge#25]
I have gotify running behind an HTTPS ingress using a Let's Encrypt cert, and the bridge gets a `x509: certificate signed by unknown authority` when trying to access it. It looks like a similar issue to #19. The CA certificates are part of the build now, but the base image hasn't been updated since then, perhaps the CA certs are too old?

**Comment by v4rakh** [comment]
I have the very same problem and would like to avoid maintaining it on my own.

```shell
Post "https://push..../message": x509: certificate signed by unknown authority
```

Any idea @DRuggeri?

**Comment by DRuggeri** [comment]
This is strange. I wouldn't think the CA certs are too old since they should be updated with every build of the docker image (can you say more about what doesn't appear to have been updated?).

What happens if you bind mount the host's certificate store into the container at `/etc/ssl/certs/ca-certificates.crt`? This should afford you more control of exactly which certs are trusted and even enable the use of internal CAs that aren't publicly trusted.

**Comment by v4rakh** [comment]
@DRuggeri Yes, that's working. Should still work without that, right. Weird.

**Comment by evandeaubl** [comment]
Working for me too. I do agree that it should work without pulling in the certs from the host system, but this is a reasonable workaround.

**Comment by DRuggeri** [comment]
I was thinking about this today - would you be comfortable sharing the endpoint that you are targeting?

Also, was hoping @evandeaubl could expand on this statement:
> The CA certificates are part of the build now, but the base image hasn't been updated since then, perhaps the CA certs are too old?

Do you mean to say that perhaps [these certs](https://github.com/DRuggeri/alertmanager_gotify_bridge/blob/master/Dockerfile#L4) are too old because the version of alpine has kept rolling forward? If so, I could probably just change the build to use the latest for this step which should pull in the latest go version and CA certs

**Comment by DRuggeri** [comment]
Nevermind - I see the issue :-)

I forgot that the GitHub workflow has a completely different Dockerfile versus building locally! Let me get that straightened out for future builds...

**Comment by DRuggeri** [comment]
I think this should be all set for the next release. I've amended the workflow in 59d594b4d346f2ea1c3e0ce34dc925515069e847 to copy certs into the target container going forward.

**Comment by evandeaubl** [comment]
Thanks much! 👍
