### ISSUE TITLE
Add Firing/Resolved to title

### ISSUE THREAD

**Issue by CubicrootXYZ** [DRuggeri/alertmanager_gotify_bridge#6]
Somehow indicate in the message if the alert message is for a firing or a resolved event.

**Comment by CubicrootXYZ** [comment]
Opened a pull request with a possible solution: https://github.com/DRuggeri/alertmanager_gotify_bridge/pull/7

**Comment by DRuggeri** [comment]
Wow - thanks, @CubicrootXYZ! I really appreciate both the idea and the contribution! I've added a few comments in the PR because I think this is a great way to solve for the need. I'll go ahead and close this issue and we can continue the conversation in the PR until it's merged.

(Sorry for the slow reply - been in and out of machine access a while)

**Comment by CubicrootXYZ** [comment]
Thanks for the kind words and no need to rush here :).

**Comment by v4rakh** [comment]
Hi, I am wondering how you get it rendered correctly in gotify. For me it outputs the HTML code in the app and that looks not very nice, still I like to have the status in the message, otherwise there's no way to distinguish between firing and resolved alerts.
Any suggestion? @CubicrootXYZ @DRuggeri?

**Comment by CubicrootXYZ** [comment]
> Hi, I am wondering how you get it rendered correctly in gotify. For me it outputs the HTML code in the app and that looks not very nice, still I like to have the status in the message, otherwise there's no way to distinguish between firing and resolved alerts.
> Any suggestion? @CubicrootXYZ @DRuggeri?

I did not use this with gotify but rather with pushbits which sends the messages to matrix where HTML rendering works.

**Comment by v4rakh** [comment]
OK. :-) Thought so, cause the project is named gotify bridge, nevertheless, I think that the parameter doesn't make much sense for gotify itself. Markdown would make sense as it can be correctly rendered within gotify or maybe I am missing something here.

TBH, I am trying to figure out how to get FIRING and RESOLVED into the messages, but I had no luck doing so. The .Status is not available inside the annotations in the alerts section of a rule of alertmanager.

**Comment by v4rakh** [comment]
Any idea how I can make this work for gotify is much appreciated. 👍
